---
title: "Untitled"
output: 

  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("mongolite")
library("rmarkdown")
library("tidyverse")
library("leaflet")
library("flexdashboard")


url="mongodb://etudiant:ur2@clusterm1-shard-00-00.0rm7t.mongodb.net:27017,clusterm1-shard-00-01.0rm7t.mongodb.net:27017,clusterm1-shard-00-02.0rm7t.mongodb.net:27017/?ssl=true&replicaSet=atlas-l4xi61-shard-0"

mdb = mongo(collection="dump_Jan2022", db="doctolib",
            url=url,
            verbose=TRUE)
            
```

```{r,echo=FALSE,include=FALSE}
requete1 <- mdb$aggregate('[
                          {
    "$geoNear": {
        "near": {"type": "Point", "coordinates": [-1.6777926, 48.117266]},
        "distanceField": "dist",
        "maxDistance": 50000
        }},
    {"$unwind":"$visit_motives"},
    {"$unwind":"$visit_motives.slots"},
    {"$match":{"visit_motives.slots":{"$gte": {"$date": "2022-01-26T00:00:00Z"},
                                      "$lt": {"$date": "2022-01-30T00:00:00Z"}}}},
    {"$group":{"_id":{"location":"$location",
                      "nom":"$name"},
               "nb_creneaux":{"$sum":1}}}
    
  
]')



```

```{r,echo=FALSE,include=FALSE}
requete2 <- mdb$aggregate('[
                          {
    "$geoNear": {
        "near": {"type": "Point", "coordinates": [-1.6777926, 48.117266]},
        "distanceField": "dist",
        "maxDistance": 50000
        }},
    {"$unwind":"$visit_motives"},
    {"$unwind":"$visit_motives.slots"},
    {"$match":{"visit_motives.slots":{"$gte": {"$date": "2022-01-01T00:00:00Z"},
                                      "$lt": {"$date": "2022-06-02T00:00:00Z"}}}},
    {"$match":{"visit_motives.first_shot_motive":true}},
    {"$group":{"_id":{"location":"$location",
                      "nom":"$name"},
               "nb_creneaux":{"$sum":1}}}
    
  
]')
```



```{r,echo=FALSE,include=FALSE}

# Mise en forme des données de la première requete

nom<- as.tibble(requete1[[1]]$nom)
nb_creneau <- as.tibble(requete1[[2]])
requete1 <- as.tibble(requete1)


coord<-t(as.data.frame(requete1[[1]]$location$coordinates))

coord <-as.tibble(coord)

result1 <- cbind(nom,coord,nb_creneau) 

colnames(result1) <- c("location","Longitude","Latitude","nb_creneaux")

```

```{r,echo=FALSE,include=FALSE}
Rennes <- c("-1.6777926","48.117266")

# La couleur dépend des nombresde créneaux en prenant les quantiles
getColor <- function(df) {
  quanti1 <- quantile(df$nb_creneaux, probs = 0.33)
  quanti2 <- quantile(df$nb_creneaux, probs = 0.66)
  sapply(df$nb_creneaux, function(nb_creneaux){
  if(nb_creneaux <= quanti1) {
    "red"
  } else if(nb_creneaux <= quanti2) {
    "orange"
  } else {
    "green"
  } })
}
```



```{r,echo=FALSE,include=FALSE}


icons1 <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = getColor(result1)
)

carte1<-leaflet(data = result1) %>% setView(lng = Rennes[1], lat = Rennes[2], zoom = 8) %>% 
  addTiles() %>%
  addAwesomeMarkers(~Longitude,~Latitude,icon=icons1, 
                    popup = ~ paste(as.character(location),"<br/>Nombre de créneaux disponibles :",as.character(nb_creneaux)))

```

```{r,echo=FALSE,include=FALSE}
# Mise en forme des données de la deuxieme requete

nom<- as.tibble(requete2[[1]]$nom)
nb_creneau <- as.tibble(requete2[[2]])
requete2 <- as.tibble(requete2)


coord<-t(as.data.frame(requete2[[1]]$location$coordinates))

coord <-as.tibble(coord)

result2 <- cbind(nom,coord,nb_creneau) 

colnames(result2) <- c("location","Longitude","Latitude","nb_creneaux")

```


```{r, echo=FALSE,include=FALSE}
icons2 <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = getColor(result2)
)

carte2<- leaflet(data = result2) %>% setView(lng = Rennes[1], lat = Rennes[2], zoom = 8) %>% 
  addTiles() %>%
  addAwesomeMarkers(~Longitude,~Latitude,icon=icons2, 
                    popup = ~ paste(as.character(location),"<br/>Nombre de créneaux disponibles :",as.character(nb_creneaux)))

```



Column {data-width=200}
-------------------------------------
    
### Choix de la carte
    
```{r,echo=FALSE}
radioButtons("graph", label = "",
    choices = c("Du 26 au 29 janvier"=1, "Du 1er janvier au 1er juin"=2), 
    selected = 1)
```
   
Column {data-width=800}
-------------------------------------
   
### Nombre de créneaux de vacinations à 50 km de Rennes en fonction de la date

```{r,echo=FALSE}
renderLeaflet({
  if (input$graph==1){
    carte1
  } else {
    carte2
  }
})
```


