---
title: "Restaurants proches de la Statue de la Liberté"
output:  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("mongolite")
library("leaflet")
```

```{r, include=FALSE}
url="mongodb://etudiant:ur2@clusterm1-shard-00-00.0rm7t.mongodb.net:27017,clusterm1-shard-00-01.0rm7t.mongodb.net:27017,clusterm1-shard-00-02.0rm7t.mongodb.net:27017/?ssl=true&replicaSet=atlas-l4xi61-shard-0"

mdb_food = mongo(collection = "NYfood", db = "food",
                 url = url,
                 verbose = TRUE)
```

```{r, echo=FALSE, include=FALSE}
requete = '[{"$geoNear":{"near": {"type": "Point", "coordinates": [-74.04450283121851, 40.68924809643922]},
                   "maxDistance": 5000, "spherical": "true", "distanceField": "dist"}}]'
donnees <- mdb_food$aggregate(pipeline = requete)
```

```{r,echo=FALSE,include=FALSE}
lon = c()
lat = c()
for (i in 1:length(donnees$address$loc$coordinate)){
  lon = c(lon, donnees$address$loc$coordinates[[c(i,1)]])
  lat = c(lat, donnees$address$loc$coordinates[[c(i,2)]])
}

donnees$address$loc['lon'] = lon
donnees$address$loc['lat'] = lat

```

```{r,echo=FALSE,include=TRUE}
pal <- colorFactor(
  palette = topo.colors(58),
  domain = donnees$cuisine
)

map_resto <- leaflet(data = donnees) %>% addTiles() %>%
  addCircleMarkers(~address$loc$lon, ~address$loc$lat, radius = 3, popup = ~paste(name, "<br>", cuisine), color = ~pal(cuisine))
map_resto
```

